# Formulario con inputs para rellenar datos

print("Introduzca el nombre:")
nombre = input()
print()
print("Introduzca el apellido:")
apellido = input()
print()
print("Introduzca su ciudad:")
ciudad = input()
print()
print("Introduzca su edad:")
edad = input ()
print()
print()
print ("tus datos son los siguientes:")
print("Nombre:", nombre)
print("Apellido", apellido)
print("Ciudad:", ciudad)
print("Edad:", edad)